### ISSUE TITLE
Can't ssh login to da0

### ISSUE THREAD

**Issue by tokey-tahmid** [cs540-24/students#75]
This is the netID.md file I submitted:
netid: ttahmid

ghid: tokey-tahmid

ssh: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKkX4pAPiLgbEiloHoD4sUraphZodk7sq49SiDx/HYKy tokeytahmid13@gmail.com

I am Tokey Tahmid. I am a Computer Science Master's student. I work as a GRA at Innovative Computing Lab (ICL). I am working on scalability of Spiking Neural Networks using High-Performance Computing. For the course project, I would like to do something using AI specially using Large Language Models (LLMs).

This is the config file I am using:
Host *
  ForwardAgent yes

Host da0
        Hostname da0.eecs.utk.edu
        Port 443
        User ttahmid
        
Note: I copied the public key from my terminal after using, "cat ~/.ssh/id_ed25519.pub". So, the ssh key matches.

Here are the permissions for my ssh directory:
-rw-r--r--@ 1 tokeytahmid  staff   260 Feb  5 11:59 config
-rw-------@ 1 tokeytahmid  staff   411 Jan  7 20:21 id_ed25519
-rw-r--r--@ 1 tokeytahmid  staff   105 Jan 24 13:01 id_ed25519.pub
-rw-------@ 1 tokeytahmid  staff  2664 Feb  5 12:14 known_hosts
-rw-------@ 1 tokeytahmid  staff  1794 Jan  9 12:26 known_hosts.old

**Comment by ozturkoktay** [comment]
Dr. @audrism please advise.

**Comment by audrism** [comment]
I need to populate the .ssh/authorized keys with the ssh key: many have been populated but not all: any chance to get a table: netid;ssk key?


Also I added this key: @tokey-tahmid lease try

**Comment by ozturkoktay** [comment]
Working on it Dr Mockus

**Comment by tokey-tahmid** [comment]
yes I am able to login now. Thank you.
